### ISSUE TITLE
How to troubleshooting 'connected' event not fired

### ISSUE THREAD

**Issue by send2vinnie** [slideme/rorschach#3]
I tried to do the distributed lock by using Rorschach but failed in the very first step - create a Rorschach instance. The event 'connected' never get fired which stops the lock acquiring processes. Is there any tips for connecting to ZooKeeper? Or any ways for troubleshooting the connection issues?

**Comment by estliberitas** [comment]
Hi. Well, the module is on very early stage, that's the reason there is no
`error` event still. I'll add it today. Currently you can only listen to
`connectionStateChanged` event which just proxies state change of
underlying ZooKeeper client' connection manager. This can help you
understand what's going on.

Also, there is a problem with `node-zookeeper-client`: it usually re-tries
anything without mentioning it. I'll update issue later today once done
with changes.

**Comment by estliberitas** [comment]
@send2vinnie Once Travis will check PRs I'll release `0.3.0` which has `error` event support. API doc is already updated.

**Comment by estliberitas** [comment]
@send2vinnie Hi, again. You can try with `npm i rorschach@0.3.0`. Also I fixed one annoying Lock bug.

**Comment by estliberitas** [comment]
@send2vinnie can I close this issue, man?
